### 1. DEFINING WORKFLOW ###
### 2. CORE COMPONENTS ###
name: Java CICD with Maven #name [optional] is displayed on your repos action page

### 3. EVENTS / TRIGGERS ###
### 4. WORKFLOW EXECUTION ###
on: #on [required] - name of GitHub event that triggers the workflow
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

# can google to see a list of events that can trigger a workflow

jobs: #jobs [required] - a set of instructions that run on the same runner; can be sequence of tasks; one or more jobs
  build: #build [required] - name of the job
  ### 5. RUNNERS ###
    runs-on: ubuntu-latest #runs-on [required] - type of runner
    steps: #steps [required] - a sequence of tasks that will be executed
    ### 6. ACTIONS ###
        - uses: actions/checkout@v4 #uses - select an action, under path action/the reusable code is hosted
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: "temurin"
            cache: maven
        - name: Build with Maven
          run: mvn -B package pom.xml
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: target-files
        - name: Display structure of downloaded files
          run: ls -R
        - name: Download artifacts
